name: pr-testing.workflow
on:
  pull_request:
    branches:
    - dev
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install msal
        pip install pytest
        set PYTHONPATH=/src/
    - name: Run tests
      run: pytest tests/test_call_sumo_api.py
