name: pytest

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: 1826bd7c-582f-4838-880d-5b4da5c3eea2
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          subscription-id: 87897772-fb27-495f-ae40-486a2df57baa
          audience: api://88d2b022-3539-4dda-9e66-853801334a86
          
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run pytest
        run: |
          access_token=$(az account get-access-token --scope api://88d2b022-3539-4dda-9e66-853801334a86/.default --query accessToken)
          echo ${#access_token}
          
          pytest -q -s --token $access_token tests/test_sumo_thin_client.py
